class Parametros:
    BLOQUETRABAJOMINIMO = 4
    BLOQUETRABAJOMAXIMO = 8
    BLOQUEALMUERZO = 6
    INICIOALMUERZOMINIMO = 16
    INICIOALMUERZOMAXIMO = 24
    DURACIONJORNADATRABAJADOR = 38
    DURACIONJORNADASUCURSAL = 46
    CANTIDADEMPLEADOS = 8
    SRC_DEMANDA = './src/Dataton2023_Etapa1.xlsx'
    ESTADOS = {'Nada': 0, 'Trabaja': 1, 'Pausa': 2, 'Almuerzo': 3}
