class Parametros:
    BLOQUETRABAJOMINIMO = 4
    BLOQUETRABAJOMAXIMO = 8
    BLOQUEALMUERZO = 6
    INICIOALMUERZOMINIMO = 16
    INICIOALMUERZOMAXIMO = 24
    DURACIONJORNADATRABAJADORTC = 34
    DURACIONJORNADATRABAJADORMT = 16
    DURACIONJORNADATRABAJADORSABADOTC = 20
    DURACIONJORNADATRABAJADORSABADOMT = 16
    DURACIONJORNADASUCURSAL = 0
    SRC_DEMANDA = './src/Dataton2023_Etapa1.xlsx'
    ESTADOS = {'Nada': 0, 'Trabaja': 1, 'Pausa': 2, 'Almuerzo': 3}
