class Parametros:
    BLOQUETRABAJOMINIMO = 4
    BLOQUETRABAJOMAXIMO = 8
    BLOQUEALMUERZO = 6
    INICIOALMUERZOMINIMO = 16
    INICIOALMUERZOMAXIMO = 24
    DURACIONJORNADATRABAJADOR = 38
    DURACIONJORNADASUCURSAL = 46
    CANTIDADEMPLEADOS = 8
